(() => {
  const humanized = {
    pt: {
      'nav.entrada': 'Entrada',
      'nav.mapa': 'Mapa',
      'nav.entregas': 'Entregas',
      'nav.ciclo': 'Ciclo',
      'nav.lastro': 'Lastro',
      'nav.packet': 'Baixar pacote',
      'packet.tip': 'Envie este arquivo para a sua IA. Ela vai te explicar, de um jeito simples, o que eu faço e onde exatamente posso ajudar você, sua equipe ou sua organização.',

      'hero.eyebrow': 'Arquitetura de Contexto Humano-IA',
      'hero.title': '<span class="hero-line">Traduzo instituições</span><span class="hero-line">em contexto que a <span class="accent">IA consegue usar.</span></span>',
      'hero.role': 'Sou psicóloga hospitalar, pós-graduada em Psicologia Organizacional e Psicopedagogia Institucional, socióloga de formação e arquiteta de contexto humano-IA.',
      'hero.tagline': 'Ajudo organizações a organizar o que já sabem e fazem, transformando documentos, rotinas, papéis, decisões e conhecimento disperso em contexto que pessoas e IA conseguem usar de verdade.',
      'hero.loc': 'Limeira / SP, Brasil',
      'hero.remote': 'Trabalho 100% remoto',
      'hero.langs': 'Português nativo · inglês avançado',
      'hero.cta1': 'Baixar pacote para sua IA',
      'hero.cta2': 'Converse comigo',

      'entrada.label': 'Como eu começo',
      'entrada.title': 'Primeiro, eu aprendo como a organização funciona de verdade.',
      'entrada.lead': 'Antes de propor qualquer uso de IA, eu preciso entender o trabalho por dentro: o que está documentado, o que vive na memória das pessoas, onde as decisões acontecem e em quais pontos o contexto costuma se perder.',
      'entrada.card1.title': 'Leitura do que já existe',
      'entrada.card1.text': 'Começo pelos materiais que a organização já usa — arquivos, protocolos, apresentações, mensagens, fluxos, planilhas, registros e regras. Eles mostram tanto o processo oficial quanto as lacunas que ficaram pelo caminho.',
      'entrada.card2.title': 'Escuta de quem sustenta o trabalho',
      'entrada.card2.text': 'Converso com pessoas-chave para entender quem sabe o quê, quem decide, quem executa, quem responde por cada frente e quais fontes podem completar o contexto quando ainda existem lacunas.',
      'entrada.card3.title': 'Leitura da rotina real',
      'entrada.card3.text': 'Observo a distância entre o fluxo previsto e o trabalho vivido: onde trava, onde alguém precisa improvisar, onde papéis se confundem e onde a IA poderia ajudar sem criar mais ruído.',
      'entrada.quote.big': 'Quase toda organização já tem inteligência. O problema é que ela costuma estar espalhada entre arquivos, pessoas, papéis e decisões.',
      'entrada.quote.text': 'Meu trabalho é reunir essa inteligência e dar a ela uma forma clara, para que equipes e ferramentas de IA consigam compreendê-la, usá-la e mantê-la viva.',

      'mapa.label': 'O que eu observo',
      'mapa.title': 'Contexto não é só documento. É gente, rotina, linguagem, responsabilidade e decisão.',
      'mapa.lead': 'Eu mapeio não apenas as fontes, mas a maneira como o trabalho realmente se sustenta: quem faz, quem sabe, quem decide, de quem cada etapa depende e onde surgem atritos, dúvidas ou vazios de responsabilidade.',
      'mapa.card1.title': 'Fontes e documentos',
      'mapa.card1.text': 'Identifico o que existe, onde está, o que ainda vale, o que ficou desatualizado e quais materiais realmente orientam o trabalho no dia a dia.',
      'mapa.card2.title': 'Fluxos e pontos de atrito',
      'mapa.card2.text': 'Acompanho como a informação e as tarefas circulam, onde algo se perde, onde nasce o retrabalho e o que as exceções revelam sobre o processo real.',
      'mapa.card3.title': 'Papéis, competências e passagens',
      'mapa.card3.text': 'Torno visível quem faz o quê, com qual autonomia, quais conhecimentos sustenta, de quem depende e onde responsabilidades se encontram, se sobrepõem ou ficam sem dono.',
      'mapa.card4.title': 'Linguagem e critérios',
      'mapa.card4.text': 'Reúno os termos, explicações e critérios que orientam decisões, para que pessoas e IA falem sobre o trabalho sem distorcer o que a organização realmente quer dizer.',
      'mapa.card5.title': 'Limites, riscos e responsabilidade',
      'mapa.card5.text': 'Deixo claro o que pode ser usado pela IA, o que precisa de revisão humana, o que é sensível e o que nunca deve ser apresentado como certeza.',
      'mapa.card6.title': 'Onde a IA pode ajudar de verdade',
      'mapa.card6.text': 'Procuro usos que reduzam ruído, facilitem entendimento, apoiem a documentação, orientem pessoas e preservem continuidade — sem automatizar só porque é possível.',

      'entregas.label': 'O que vira entrega',
      'entregas.title': 'O que estava espalhado vira uma base clara, revisável e pronta para ser usada.',
      'entregas.lead': 'A entrega não é um amontoado de notas. É uma camada de contexto organizada para reduzir repetição, esclarecer responsabilidades e ajudar pessoas e IA a responder, decidir e trabalhar com mais segurança.',
      'entregas.card1.title': 'Mapa contextual da organização',
      'entregas.card1.text': 'Um retrato legível do cenário: objetivos, fontes, fluxos, pessoas, decisões, riscos, linguagem, papéis e prioridades — com as conexões que ajudam tudo isso a fazer sentido.',
      'entregas.card2.title': 'Mapa de papéis, competências e interfaces',
      'entregas.card2.text': 'Uma visão clara de quem faz o quê, com qual autonomia, quais conhecimentos sustenta, de quem depende e onde existem lacunas, sobreposições ou passagens de responsabilidade que precisam de cuidado.',
      'entregas.card3.title': 'Pacote de orientação para sua IA',
      'entregas.card3.text': 'Um material que ensina a sua IA a compreender aquele contexto: quais fontes consultar, que linguagem usar, quais limites respeitar e como responder sem inventar segurança onde ela não existe.',
      'entregas.card4.title': 'Documentação viva',
      'entregas.card4.text': 'Registros feitos para acompanhar a realidade: mostram o que vale agora, o que mudou, o que precisa de revisão e como preservar continuidade mesmo quando pessoas e processos mudam.',
      'entregas.card5.title': 'Especificação de assistentes internos',
      'entregas.card5.text': 'Antes de transformar IA em rotina ou produto, deixo claros o propósito, os usuários, as tarefas, os riscos, os limites e o padrão de resposta esperado.',
      'entregas.card6.title': 'Critérios de revisão, responsabilidade e segurança',
      'entregas.card6.text': 'Organizo a diferença entre fato, inferência, decisão, preferência, autorização, risco e promessa — e deixo claro quem precisa revisar ou responder por cada ponto.',

      'ciclo.label': 'Depois do mapa',
      'ciclo.title': 'O contexto só funciona quando é testado, cuidado e atualizado.',
      'ciclo.lead': 'Depois de aprender a organização e construir a primeira estrutura, eu valido o material com quem conhece o trabalho, testo em tarefas reais e ajusto o que for necessário. Contexto bom não fica congelado: acompanha a organização.',
      'ciclo.fase1.label': 'Fase 1',
      'ciclo.fase1.title': 'Aprender',
      'ciclo.fase1.text': 'Entro nos materiais, nas conversas e nas rotinas para compreender o cenário antes de desenhar qualquer solução.',
      'ciclo.fase2.label': 'Fase 2',
      'ciclo.fase2.title': 'Estruturar',
      'ciclo.fase2.text': 'Transformo o que foi aprendido em mapas, pacotes, critérios, modelos de responsabilidade e documentos que possam ser usados de verdade.',
      'ciclo.fase3.label': 'Fase 3',
      'ciclo.fase3.title': 'Validar e testar',
      'ciclo.fase3.text': 'Coloco a estrutura diante de quem vive o trabalho e em tarefas reais, para verificar se ela é clara, útil e segura — não apenas bonita no papel.',
      'ciclo.fase4.label': 'Fase 4',
      'ciclo.fase4.title': 'Manter',
      'ciclo.fase4.text': 'Acompanho mudanças, corrijo desvios, reviso fontes e incorporo o retorno da equipe para que o contexto continue confiável.',
      'ciclo.fase5.label': 'Fase 5',
      'ciclo.fase5.title': 'Aperfeiçoar',
      'ciclo.fase5.text': 'Refino respostas, fluxos, treinamentos, critérios e rotinas à medida que o uso real mostra novas necessidades e possibilidades.',

      'lastro.label': 'Por que eu',
      'lastro.title': 'Meu diferencial é compreender pessoas e instituições — e transformar essa leitura em estrutura útil para a IA.',
      'lastro.lead': 'Eu não entro como engenheira de modelos. Entro como alguém que entende pessoas, papéis, conflitos, aprendizagem, linguagem, memória e rotina institucional — e sabe organizar tudo isso para que tecnologia e trabalho humano se encontrem melhor.',
      'lastro.card1.title': 'Psicologia Organizacional',
      'lastro.card1.text': 'Uso a leitura de equipes, papéis, autonomia, responsabilidade, cultura, poder, comunicação e colaboração para compreender não apenas o processo, mas as pessoas que o fazem acontecer.',
      'lastro.card2.title': 'Psicopedagogia Institucional',
      'lastro.card2.text': 'Desenho formas de aprender e usar IA dentro da rotina, com linguagem acessível e treinamento conectado ao trabalho — não como uma palestra abstrata que termina sem mudar nada.',
      'lastro.card3.title': 'Mediação de conflitos',
      'lastro.card3.text': 'Reconheço tensões, disputas de papel, sobrecarga e falhas de comunicação que podem bloquear a colaboração ou transformar uma boa ferramenta em mais um problema.',
      'lastro.card4.title': 'Governança de conhecimento',
      'lastro.card4.text': 'Organizo fontes, versões, decisões, mudanças, autoria, privacidade e responsabilidades para que o conhecimento continue confiável em vez de envelhecer silenciosamente.',
      'lastro.card5.title': 'Pesquisa e linguagem estratégica',
      'lastro.card5.text': 'Investigo informação fragmentada, encontro as fontes certas e transformo complexidade em briefings, textos e handoffs claros, humanos e defendíveis.',
      'lastro.card6.title': 'Sistemas de uso com IA',
      'lastro.card6.text': 'Crio assistentes, critérios de resposta, revisores, motores visuais, pacotes de continuidade e rotinas de qualidade voltados para necessidades concretas.',
      'lastro.boundary.big': 'Eu não desenvolvo o modelo. Construo a camada que ajuda pessoas e IA a não trabalharem no vazio.',
      'lastro.boundary.text': 'Meu trabalho se encaixa ao lado de equipes técnicas, produtos, Gestão de Pessoas e Talentos, desenho organizacional, saúde, educação, setor público e projetos que precisam compreender melhor o próprio conhecimento antes de automatizar.',
      'lastro.tag1': 'adoção de IA',
      'lastro.tag2': 'memória operacional',
      'lastro.tag3': 'papéis e competências',
      'lastro.tag4': 'documentação viva',
      'lastro.tag5': 'uso responsável',
      'lastro.tag6': 'sistemas de pessoas e talentos',
      'lastro.tag7': 'pesquisa e tradução institucional',

      'contact.quote': 'Toda instituição já tem uma inteligência própria. Eu ajudo a reuni-la, organizá-la e torná-la legível para pessoas e IA.',
      'contact.title': 'Vamos entender onde eu posso ajudar?',
      'contact.sub': 'Se a sua organização, produto ou projeto precisa organizar conhecimento, esclarecer papéis, preservar contexto ou encontrar usos mais responsáveis e úteis para a IA, podemos adaptar esse trabalho à sua realidade.',
      'contact.packet': 'Baixar pacote para sua IA',
      'foot.rights': 'Arquitetura de Contexto Humano-IA · Limeira/SP · trabalho remoto'
    },

    en: {
      'nav.entrada': 'Entry',
      'nav.mapa': 'Map',
      'nav.entregas': 'Outputs',
      'nav.ciclo': 'Cycle',
      'nav.lastro': 'Foundation',
      'nav.packet': 'Download packet',
      'packet.tip': 'Send this file to your AI. It will explain, in plain language, what I do and exactly where I could help you, your team, or your organization.',

      'hero.eyebrow': 'Human–AI Context Architecture',
      'hero.title': '<span class="hero-line">I translate institutions</span><span class="hero-line">into context <span class="accent">AI can actually use.</span></span>',
      'hero.role': 'I am a hospital psychologist, postgraduate-trained in Organizational Psychology and Institutional Psychopedagogy, a sociologist by training, and a Human–AI Context Architect.',
      'hero.tagline': 'I help organizations make sense of what they already know and do, turning documents, routines, roles, decisions, and scattered knowledge into context that people and AI can genuinely use.',
      'hero.loc': 'Limeira / São Paulo, Brazil',
      'hero.remote': 'I work 100% remotely',
      'hero.langs': 'Native Brazilian Portuguese · advanced English',
      'hero.cta1': 'Download a packet for your AI',
      'hero.cta2': 'Talk to me',

      'entrada.label': 'How I begin',
      'entrada.title': 'First, I learn how the organization really works.',
      'entrada.lead': 'Before proposing any use of AI, I need to understand the work from the inside: what is documented, what lives in people’s memory, where decisions happen, and where context tends to get lost.',
      'entrada.card1.title': 'Reading what already exists',
      'entrada.card1.text': 'I begin with the materials the organization already uses — files, protocols, presentations, messages, workflows, spreadsheets, records, and rules. They reveal both the official process and the gaps left along the way.',
      'entrada.card2.title': 'Listening to the people who sustain the work',
      'entrada.card2.text': 'I speak with key people to understand who knows what, who decides, who executes, who owns each front, and which sources can complete the picture when gaps remain.',
      'entrada.card3.title': 'Reading the real routine',
      'entrada.card3.text': 'I look at the distance between the intended workflow and lived work: where it stalls, where people improvise, where roles blur, and where AI could help without creating more noise.',
      'entrada.quote.big': 'Almost every organization already has intelligence. The problem is that it is usually scattered across files, people, roles, and decisions.',
      'entrada.quote.text': 'My work is to gather that intelligence and give it a clear form, so human teams and AI tools can understand it, use it, and keep it alive.',

      'mapa.label': 'What I look at',
      'mapa.title': 'Context is not only documentation. It is people, routine, language, responsibility, and decisions.',
      'mapa.lead': 'I map not only the sources, but how the work actually holds together: who does it, who knows it, who decides, what each step depends on, and where friction, uncertainty, or gaps in ownership appear.',
      'mapa.card1.title': 'Sources and documents',
      'mapa.card1.text': 'I identify what exists, where it lives, what is still current, what has become outdated, and which materials truly guide everyday work.',
      'mapa.card2.title': 'Workflows and friction points',
      'mapa.card2.text': 'I follow how information and tasks move, where something gets lost, where rework begins, and what exceptions reveal about the real process.',
      'mapa.card3.title': 'Roles, capabilities, and handoffs',
      'mapa.card3.text': 'I make visible who does what, with what autonomy, which knowledge they hold, who they depend on, and where responsibilities meet, overlap, or remain unowned.',
      'mapa.card4.title': 'Language and criteria',
      'mapa.card4.text': 'I gather the terms, explanations, and criteria that guide decisions, so people and AI can discuss the work without distorting what the organization actually means.',
      'mapa.card5.title': 'Boundaries, risks, and accountability',
      'mapa.card5.text': 'I make clear what AI can use, what needs human review, what is sensitive, and what must never be presented as certain.',
      'mapa.card6.title': 'Where AI can genuinely help',
      'mapa.card6.text': 'I look for uses that reduce noise, make understanding easier, support documentation, guide people, and preserve continuity — without automating simply because it is possible.',

      'entregas.label': 'What becomes an output',
      'entregas.title': 'What was scattered becomes a clear, reviewable foundation ready to be used.',
      'entregas.lead': 'The output is not a pile of notes. It is an organized context layer designed to reduce repetition, clarify responsibility, and help people and AI respond, decide, and work more safely.',
      'entregas.card1.title': 'Organizational context map',
      'entregas.card1.text': 'A readable picture of the landscape: goals, sources, workflows, people, decisions, risks, language, roles, and priorities — including the connections that make them meaningful.',
      'entregas.card2.title': 'Role, capability, and interface map',
      'entregas.card2.text': 'A clear view of who does what, with what autonomy, which knowledge they hold, who they depend on, and where gaps, overlaps, or handoffs need attention.',
      'entregas.card3.title': 'Orientation packet for your AI',
      'entregas.card3.text': 'A material that teaches your AI how to understand that context: which sources to consult, what language to use, which boundaries to respect, and how to answer without pretending to know more than it does.',
      'entregas.card4.title': 'Living documentation',
      'entregas.card4.text': 'Records designed to follow reality: what is current, what changed, what needs review, and how continuity can survive changes in people and processes.',
      'entregas.card5.title': 'Internal assistant specification',
      'entregas.card5.text': 'Before AI becomes a routine or product, I clarify its purpose, users, tasks, risks, boundaries, and expected response standards.',
      'entregas.card6.title': 'Review, accountability, and safety criteria',
      'entregas.card6.text': 'I organize the difference between fact, inference, decision, preference, authorization, risk, and promise — and make clear who needs to review or own each point.',

      'ciclo.label': 'After the map',
      'ciclo.title': 'Context only works when it is tested, cared for, and kept current.',
      'ciclo.lead': 'After learning the organization and building the first structure, I validate it with people who know the work, test it in real tasks, and adjust what needs adjustment. Good context does not stay frozen; it changes with the organization.',
      'ciclo.fase1.label': 'Phase 1',
      'ciclo.fase1.title': 'Learn',
      'ciclo.fase1.text': 'I enter the materials, conversations, and routines to understand the landscape before designing any solution.',
      'ciclo.fase2.label': 'Phase 2',
      'ciclo.fase2.title': 'Structure',
      'ciclo.fase2.text': 'I turn what was learned into maps, packets, criteria, ownership models, and documents people can genuinely use.',
      'ciclo.fase3.label': 'Phase 3',
      'ciclo.fase3.title': 'Validate and test',
      'ciclo.fase3.text': 'I put the structure in front of people who live the work and into real tasks, checking whether it is clear, useful, and safe — not merely elegant on paper.',
      'ciclo.fase4.label': 'Phase 4',
      'ciclo.fase4.title': 'Maintain',
      'ciclo.fase4.text': 'I follow changes, correct drift, review sources, and bring in team feedback so the context remains trustworthy.',
      'ciclo.fase5.label': 'Phase 5',
      'ciclo.fase5.title': 'Improve',
      'ciclo.fase5.text': 'I refine responses, workflows, training, criteria, and routines as real use reveals new needs and possibilities.',

      'lastro.label': 'Why me',
      'lastro.title': 'My edge is understanding people and institutions — and turning that understanding into useful structure for AI.',
      'lastro.lead': 'I do not enter as a model engineer. I enter as someone who understands people, roles, conflict, learning, language, memory, and institutional routine — and knows how to organize them so technology and human work can meet more effectively.',
      'lastro.card1.title': 'Organizational Psychology',
      'lastro.card1.text': 'I use an understanding of teams, roles, autonomy, responsibility, culture, power, communication, and collaboration to read not only the process, but the people who make it happen.',
      'lastro.card2.title': 'Institutional Psychopedagogy',
      'lastro.card2.text': 'I design ways to learn and use AI within the routine, with accessible language and training connected to real work — not an abstract lecture that ends without changing anything.',
      'lastro.card3.title': 'Conflict mediation',
      'lastro.card3.text': 'I recognize tensions, role disputes, overload, and communication failures that can block collaboration or turn a useful tool into one more problem.',
      'lastro.card4.title': 'Knowledge governance',
      'lastro.card4.text': 'I organize sources, versions, decisions, changes, authorship, privacy, and ownership so knowledge remains trustworthy instead of quietly becoming outdated.',
      'lastro.card5.title': 'Research and strategic language',
      'lastro.card5.text': 'I investigate fragmented information, find the right sources, and turn complexity into clear, human, and defensible briefs, texts, and handoffs.',
      'lastro.card6.title': 'AI-use systems',
      'lastro.card6.text': 'I create assistants, response criteria, reviewers, visual engines, continuity packets, and quality routines built around concrete needs.',
      'lastro.boundary.big': 'I do not develop the model. I build the layer that keeps people and AI from working in a vacuum.',
      'lastro.boundary.text': 'My work fits alongside technical teams, products, People & Talent, organizational design, healthcare, education, the public sector, and projects that need to understand their own knowledge before automating it.',
      'lastro.tag1': 'AI adoption',
      'lastro.tag2': 'operational memory',
      'lastro.tag3': 'roles and capabilities',
      'lastro.tag4': 'living documentation',
      'lastro.tag5': 'responsible use',
      'lastro.tag6': 'People & Talent systems',
      'lastro.tag7': 'research and institutional translation',

      'contact.quote': 'Every institution already has its own intelligence. I help gather it, organize it, and make it legible to people and AI.',
      'contact.title': 'Shall we find where I can help?',
      'contact.sub': 'If your organization, product, or project needs to organize knowledge, clarify roles, preserve context, or find more useful and responsible ways to use AI, we can adapt this work to your reality.',
      'contact.packet': 'Download a packet for your AI',
      'foot.rights': 'Human–AI Context Architecture · Limeira/SP · remote work'
    }
  };

  if (typeof T === 'object' && T.pt && T.en) {
    Object.assign(T.pt, humanized.pt);
    Object.assign(T.en, humanized.en);
  }

  document.querySelectorAll('[data-discord]').forEach((button) => {
    button.setAttribute('data-discord', 'moon_aurea');
  });

  if (typeof applyLang === 'function' && typeof getLang === 'function') {
    applyLang(getLang());
  }
})();
