(() => {
  const copy = {
    pt: {
      title:'Lua Helena Moon · Contexto, Adoção e Auditoria de IA · V10 beta', eyebrow:'Arquitetura Contextual, Adoção e Auditoria de IA',
      methodKicker:'Como eu trabalho', methodTitle:'Entender o campo antes de escolher a forma.', methodLead:'O método é simples de explicar e rigoroso de executar: entender a realidade, estruturar o contexto necessário e manter a solução corrigível quando a realidade muda.',
      step1:'Entender', step1p:'Mapear fontes, pessoas, fluxos, autoridade, fricções e limites antes de automatizar.', step2:'Estruturar', step2p:'Dar ao contexto a menor forma útil: fonte viva, mapa, handoff, protocolo, base ou combinação proporcional.', step3:'Validar e manter', step3p:'Testar uso real, revisar falhas, atualizar por delta e impedir que material antigo governe o presente.',
      methodDrawer:'Ver a arquitetura de método em detalhe', legacyIntro:'As seções detalhadas da V9.1 continuam preservadas nesta gaveta; a superfície principal apenas deixou de exigir que todo visitante as leia.',
      proofKicker:'Prova pública', proofTitle:'A arquitetura pode ser inspecionada.', proofLead:'Em vez de pedir que você confie em adjetivos, mantenho corpos públicos que mostram partes diferentes do trabalho.',
      sourceTitle:'Contexto governado e reutilizável.', sourceText:'Moon Source é a arquitetura pública de referência para fontes, autoridade, memória, continuidade, handoffs, atualização e passagem de contexto entre pessoas e IA.', sourceDrawer:'Detalhes para quem trabalha com contexto e IA', sourceOpen:'Explorar Moon Source',
      cortexTitle:'Sistemas aplicados sobre contexto governado.', cortexText:'Moon Cortex demonstra como mecanismos situados podem ser generalizados em sistemas públicos independentes, com privacidade, proveniência, limites e soberania do usuário.', cortexDrawer:'Detalhes para quem trabalha com sistemas e generalização', cortexOpen:'Abrir Moon Cortex no GitHub', cortexSystems:'Sistemas públicos atuais', beta:'V10 beta'
    },
    en: {
      title:'Lua Helena Moon · Context Architecture, AI Adoption and Auditing · V10 beta', eyebrow:'Context Architecture, AI Adoption and Auditing',
      methodKicker:'How I work', methodTitle:'Understand the field before choosing the form.', methodLead:'The method is simple to explain and rigorous to execute: understand reality, structure the context that is actually needed, and keep the solution corrigible as reality changes.',
      step1:'Understand', step1p:'Map sources, people, workflows, authority, friction, and boundaries before automating.', step2:'Structure', step2p:'Give context the smallest useful form: a living source, map, handoff, protocol, knowledge base, or a proportionate combination.', step3:'Validate and maintain', step3p:'Test real use, review failures, update by delta, and prevent old material from quietly governing the present.',
      methodDrawer:'See the method architecture in detail', legacyIntro:'The detailed V9.1 sections remain preserved inside this drawer; the main surface simply no longer requires every visitor to read them.',
      proofKicker:'Public proof', proofTitle:'The architecture can be inspected.', proofLead:'Rather than asking you to trust adjectives, I maintain public bodies that expose different parts of the work.',
      sourceTitle:'Governed, reusable context.', sourceText:'Moon Source is the public reference architecture for sources, authority, memory, continuity, handoffs, updates, and context passage between people and AI.', sourceDrawer:'Details for people who work with context and AI', sourceOpen:'Explore Moon Source',
      cortexTitle:'Applied systems over governed context.', cortexText:'Moon Cortex shows how situated mechanisms can be generalized into independent public systems with privacy, provenance, boundaries, and user sovereignty.', cortexDrawer:'Details for people who work with systems and generalization', cortexOpen:'Open Moon Cortex on GitHub', cortexSystems:'Current public systems', beta:'V10 beta'
    }
  };
  const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>[...r.querySelectorAll(s)];
  const lang=()=>document.documentElement.lang==='en'||q('.lang-toggle button[data-lang="en"]')?.classList.contains('active')?'en':'pt';

  const methodMarkup=()=>`<section class="v10-method wrap reveal" id="metodo-v10"><div class="v10-method-head"><div class="v10-kicker" data-v10="methodKicker"></div><h2 data-v10="methodTitle"></h2><p data-v10="methodLead"></p></div><div class="v10-steps"><article class="v10-step"><span class="v10-step-num">01</span><h3 data-v10="step1"></h3><p data-v10="step1p"></p></article><article class="v10-step"><span class="v10-step-num">02</span><h3 data-v10="step2"></h3><p data-v10="step2p"></p></article><article class="v10-step"><span class="v10-step-num">03</span><h3 data-v10="step3"></h3><p data-v10="step3p"></p></article></div><details class="v10-drawer" id="metodo-detalhes"><summary data-v10="methodDrawer"></summary><div class="v10-drawer-body"><p data-v10="legacyIntro"></p><div class="v10-legacy-detail" data-v10-legacy></div></div></details></section>`;
  const proofMarkup=()=>`<section class="v10-proof wrap reveal" id="prova-publica"><div class="v10-kicker" data-v10="proofKicker"></div><h2 data-v10="proofTitle"></h2><p class="v10-proof-lead" data-v10="proofLead"></p><div class="v10-proof-grid"><article class="v10-proof-card" data-proof="source"><div class="v10-proof-eyebrow"><span aria-hidden="true">🌙</span>Moon Source</div><h3 data-v10="sourceTitle"></h3><p data-v10="sourceText"></p><div class="v10-proof-tags"><span>governed context</span><span>source authority</span><span>continuity</span><span>knowledge governance</span></div><div class="v10-proof-actions"><a class="btn btn-primary" href="https://www.luahelena.com.br/moonsource/" target="_blank" rel="noopener" data-v10="sourceOpen"></a><a class="btn" href="https://github.com/luahelenammc/Moon-Source" target="_blank" rel="noopener">GitHub ↗</a></div><details class="v10-drawer"><summary data-v10="sourceDrawer"></summary><div class="v10-drawer-body"><div class="v10-tech-list"><span>Source authority & jurisdiction</span><span>Freshness & living sources</span><span>Handoffs & context packets</span><span>Connected-source governance</span><span>Source hygiene & provenance</span><span>Lifecycle, readback & MSL</span></div></div></details></article><article class="v10-proof-card" data-proof="cortex"><div class="v10-proof-eyebrow"><span aria-hidden="true">◌</span>Moon Cortex</div><h3 data-v10="cortexTitle"></h3><p data-v10="cortexText"></p><div class="v10-proof-tags"><span>generalization</span><span>privacy stripping</span><span>domain systems</span><span>bounded validation</span></div><div class="v10-proof-actions"><a class="btn btn-primary" href="https://github.com/luahelenammc/Moon-Cortex" target="_blank" rel="noopener" data-v10="cortexOpen"></a></div><details class="v10-drawer"><summary data-v10="cortexDrawer"></summary><div class="v10-drawer-body"><strong data-v10="cortexSystems"></strong><div class="v10-tech-list"><span>Financial Living System</span><span>Social Support Navigation System</span><span>Invariant extraction</span><span>Donor/privacy stripping</span><span>Domain-shaped contracts</span><span>Source/system boundaries</span></div></div></details></article></div></section>`;

  function hero(){
    const role=q('.role'); if(!role||q('.positioning-stack')) return;
    role.outerHTML=`<div class="positioning-stack" aria-label="Professional positioning"><p class="market-position-detail" data-v10-hero="detail"></p><p class="professional-foundation" data-v10-hero="foundation"></p><div class="hero-proof-links"><a class="hero-proof-link" href="https://www.luahelena.com.br/moonsource/" target="_blank" rel="noopener"><span>🌙</span><span data-v10-hero="source"></span><span>↗</span></a><a class="hero-proof-link" href="https://github.com/luahelenammc/Moon-Cortex" target="_blank" rel="noopener"><span>◌</span><span data-v10-hero="cortex"></span><span>↗</span></a></div></div>`;
  }
  function install(){
    if(document.body.dataset.v10Installed) return; document.body.dataset.v10Installed='true'; hero();
    const entrada=document.getElementById('entrada'); if(!entrada) return;
    if(!document.getElementById('metodo-v10')) entrada.insertAdjacentHTML('afterend',methodMarkup());
    const campos=document.getElementById('campos'), publicos=document.getElementById('publicos'), method=document.getElementById('metodo-v10');
    if(campos) entrada.insertAdjacentElement('afterend',campos); if(publicos&&campos) campos.insertAdjacentElement('afterend',publicos); if(method) (publicos||campos||entrada).insertAdjacentElement('afterend',method);
    const legacy=q('[data-v10-legacy]',method); ['mapa','entregas','ciclo'].forEach(id=>{const el=document.getElementById(id); if(el&&legacy) legacy.appendChild(el)});
    const lastro=document.getElementById('lastro'); if(!document.getElementById('prova-publica')) (lastro||method).insertAdjacentHTML('beforebegin',proofMarkup());
    document.getElementById('moon-source-proof')?.remove();
    const nav=q('.nav-links'); if(nav&&!q('.nav-v10',nav)){nav.insertAdjacentHTML('beforeend','<a href="#campos" class="nav-v10" data-nav-v10="apps"></a><a href="#metodo-v10" class="nav-v10" data-nav-v10="method"></a><a href="#prova-publica" class="nav-v10" data-nav-v10="proof"></a>')}
    if(!q('.beta-ribbon')) document.body.insertAdjacentHTML('beforeend','<div class="beta-ribbon" data-v10="beta">V10 beta</div>');
    qa('.reveal').forEach(el=>el.classList.add('show')); apply(); if(window.lucide) window.lucide.createIcons();
  }
  function apply(){
    const L=lang(), c=copy[L]; document.title=c.title; qa('[data-v10]').forEach(el=>{const k=el.dataset.v10;if(c[k])el.textContent=c[k]});
    const eyebrow=q('[data-i="hero.eyebrow"]'); if(eyebrow) eyebrow.textContent=c.eyebrow;
    const h={pt:{detail:'A IA pode produzir uma resposta convincente sem que ela seja verdadeira. Eu estruturo fontes, bases de conhecimento e critérios responsáveis para que responda com base sólida, e audito também se a solução funciona no trabalho real e para as pessoas.',foundation:'Sou graduada em Psicologia e em Sociologia, com pós-graduação em Psicologia Organizacional e em Psicopedagogia Institucional. Como psicóloga hospitalar, trabalho em sistemas complexos, fluxos institucionais, equipes multiprofissionais, informação sensível e decisões que exigem responsabilidade.',source:'Moon Source · arquitetura pública de contexto',cortex:'Moon Cortex · sistemas públicos aplicados'},en:{detail:'AI can produce a convincing answer without it being true. I structure reliable sources, knowledge bases, and responsible criteria so it can answer from solid ground, and I also audit whether the solution works in real operations and for people.',foundation:'I hold degrees in Psychology and Sociology, with postgraduate qualifications in Organizational Psychology and Institutional Psychopedagogy. As a hospital psychologist, I work in complex systems involving institutional workflows, multidisciplinary teams, sensitive information, and accountable decisions.',source:'Moon Source · public context architecture',cortex:'Moon Cortex · public applied systems'}}[L];
    qa('[data-v10-hero]').forEach(el=>el.textContent=h[el.dataset.v10Hero]);
    const n={apps:L==='en'?'Applications':'Aplicações',method:L==='en'?'Method':'Método',proof:L==='en'?'Public proof':'Prova pública'}; qa('[data-nav-v10]').forEach(el=>el.textContent=n[el.dataset.navV10]);
  }
  const ready=()=>{requestAnimationFrame(()=>requestAnimationFrame(install));setTimeout(install,80)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
  document.addEventListener('click',e=>{if(e.target.closest('.lang-toggle button'))setTimeout(apply,0)}); new MutationObserver(apply).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});
})();
